app = 'fox-ears'
primary_region = 'sea'

[build]
  dockerfile = './Dockerfile'
  ignorefile = './.dockerignore'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = 'requests'
    soft_limit = 1000
    hard_limit = 1250

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
