apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cat-ears
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/execution-environment: gen1
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containers:
      - image: "$REGION-docker.pkg.dev/$PROJECT/docker-images/catears:latest"
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
      containerConcurrency: 1000
